### ISSUE TITLE
Tests for publicationYear form field

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#141]
Child of #140.

**Comment by kjgarza** [comment]
Started with the Rendering test but there seems to be something i'm missing, will need to investigate further.


error:

```
            { type: 'error',
              testContext:
               { id: 3,
                 name: 'Integration | Component | doi-form: it rejects non integers',
                 items: [],
                 state: 'executing' },
              text: 'Uncaught TypeError: Cannot read property \'get\' of undefined at http://localhost:7357/assets/bracco.js, line 2764\n' }
    ...
not ok 6 Chrome 72.0 - [178 ms] - Integration | Component | doi-form: it rejects non integers
    ---
        actual: >
            null
        stack: >
            http://localhost:7357/assets/bracco.js:2764
        message: >
            Uncaught TypeError: Cannot read property 'get' of undefined
        negative: >
            false
        Log: |
    ...


```


spec

```
  test('it rejects non integers', async function(assert) {
    assert.expect(1);

    this.set('publicationYear', 'red');
    await render(hbs`{{doi-form}}`);

    assert.equal(this.element.querySelector("div.help-block").innerText, 'Must be between 1450 and 2020.');
    assert.equal(this.element.querySelector("label.control-label.col-md-3").getAttribute('style'), 'color: #e74c3c');
  });

```

**Comment by mfenner** [comment]
Use `assert.dom`. https://github.com/simplabs/qunit-dom

**Comment by kjgarza** [comment]
Questions:
- Can I fully separate the the form into components.  Fields such as Publisher and Publicationyear are in the doi-form component. this means that we have to test the whole form to tests those component ?
https://github.com/datacite/bracco/blob/ae3967df32010c18e6ae67098699670cf9b027df/app/templates/components/doi-form.hbs#L18
- I would like to have very clear the Testing Specs. I prepared some intial specs https://github.com/datacite/bracco/issues/140 . But I would like to feedback.
- How do we deal with refractoring?

Blockers:
- I have not been able to render ember-bootstrap elemnts (`form.element`). 
  - I think its because some elements do not stand on their own. for example, doesn't have the surounder form field https://github.com/datacite/bracco/blob/ae3967df32010c18e6ae67098699670cf9b027df/app/templates/components/doi-titles.hbs#L1
	- richard pointout that I can replicate the enclosing element in the form
- Even when adding enclosing elements. I canot render the bs-form at the moment.

**Comment by kjgarza** [comment]
allowed value 73fb618e20a0e85a4ec1e55be68d3217af500ae0
multiple values N/A
missing value a261d08aa2a75d648fdc2b853a7388474e9f2fdd
incorrect value(s) a261d08aa2a75d648fdc2b853a7388474e9f2fdd
insufficient permissions N/A
adding/editing/deleting of values in c52107fa840f9da966960490c4dd057f66fb6c3c
