### ISSUE TITLE
Support for seriesInformation

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#162]
Child of #155.

**Comment by daslerr** [comment]
The DataCite Metadata Schema currently does not support certain fields necessary for citation of journal articles (and other similar serial text publications). We typically advise members and clients to put this information into a `description` field using the descriptionType `seriesInformation` instead, but since this field is free text, that information is input inconsistently. 

It would help for the future if we could at least capture this information in a consistent way. We will add special handling to the Fabrica form for the `seriesInformation` descriptionType. When the `seriesInformation` descriptionType is selected, the input box will change from the paragraph text input box to a series of smaller fields for article citation properties. The values input into these fields will be stored as a comma-separated list. 

These smaller fields are: 
- Journal Title
- Volume Number
- Issue Number
- Start Page Number
- End Page Number

See wireframes:
![Screenshot 2019-03-11 at 09 12 07](https://user-images.githubusercontent.com/3181623/54109063-e2001380-43dd-11e9-964d-4ec5dab88e6c.png)

**Comment by mfenner** [comment]
seriesInformation is parsed in the API using this code https://github.com/datacite/bolognese/blob/master/lib/bolognese/readers/datacite_reader.rb#L221-L240 and this code https://github.com/datacite/bolognese/blob/master/lib/bolognese/utils.rb#L914-L933.

Briefly, we parse `description` type `seriesInformation` and split the contents of the field using `,`, returning (series-)title, volume/issue, and page numbers. Volume issue is further parsed, assuming the format `2(9)`. Page numbers has the format `12-24` and is then further split internally into first page and last page. So an example string would be:

```
DataCite Blog, 2(9), 3-4
```

**Comment by richardhallett** [comment]
Due the fact the schema does not support seperate fields for series information and to avoid backwards incompatability problems, I've added a warning in place that looks for our specific format.
This is only a warning and only applies when SeriesInformation is chosen.
