### ISSUE TITLE
Not possible to delete repository INIST.SIDR

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#366]
Delete INIST.SIDR

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1fw77)

**Comment by richardhallett** [comment]
There were 9 hidden DOI's that were not being parsed correctly, this was due to version 2 metadata schema. I've manually updated them and now they can be transferred somewhere as appropriate.
After deleting will work.

DOIS:
10.4123/SIDR.000006M.RP
10.4123/SIDR.000006G.RP
10.4123/SIDR.000004P.RP
10.4123/SIDR.000004N.RP
10.4123/SIDR.000004E.RP
10.4123/SIDR.000004C.RP
10.4123/SIDR.000004B.RP
10.4123/SIDR.0000049.RP
10.4123/SIDR.000002X.RP
