### ISSUE TITLE
Feedback DOI Form

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#395]
* Description should be grouped under "Recommended Fields"
* Consistency whether optional fields are shown with empty values (e.g. Dates), or just have an "Add another something" button
* Remove "Size (optional)", "Format (optional)", "Date (optional)", "Date information (optional)" right above input fields
* Selecting contributor type should set name type where appropriate, e.g. RegistrationAgency -> Organization
* Consistent case, e.g. "Add another contributor" instead of "Add another Contributor". Same for "Add Related Identifier" and "Add Alternate Identifier"
* Award URI instead of Award Uri
* "Add another funding reference" instead of "Add another funder reference"
* Validate URL in "Award URI"
* Fix spacing after "Funder name" and "Funder identifier type" blocks
* Add label above input box for "Alternate identifier"
* Where is geolocation information other than geolocation place?
* Make contributor types human-readable (Registration agency instead of RegistrationAgency)
* geolocation instead of geo location
* Validation date field

**Comment by kjgarza** [comment]
- [ ] Description should be grouped under "Recommended Fields"
- [ ] Consistency whether optional fields are shown with empty values (e.g. Dates), or just have an "Add another something" button
- [ ] Remove "Size (optional)", "Format (optional)", "Date (optional)", "Date information (optional)" right above input fields
- [ ]  Selecting contributor type should set name type where appropriate, e.g. RegistrationAgency -> Organization
- [ ] Consistent case, e.g. "Add another contributor" instead of "Add another Contributor". Same for "Add Related Identifier" and "Add Alternate Identifier"
- [ ] Award URI instead of Award Uri
- [ ] "Add another funding reference" instead of "Add another funder reference"
- [ ] Validate URL in "Award URI"
- [ ] Fix spacing after "Funder name" and "Funder identifier type" blocks
- [ ] Add label above input box for "Alternate identifier"
- [ ] Where is geolocation information other than geolocation place?
- [ ] Make contributor types human-readable (Registration agency instead of RegistrationAgency)
- [ ] geolocation instead of geo location
- [ ] Validation date field
