### ISSUE TITLE
Not possible to navigate to DOIs tab 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#396]
### Expected Behaviour

DOIs listed under DOIs tab

### Current Behaviour

For some accounts the DOIs are not listed https://doi.test.datacite.org/providers/osi 

### Steps to Reproduce

1. Example https://doi.test.datacite.org/providers/osi

### Context (Environment)

Fabrica test

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nnit)

**Comment by mfenner** [comment]
This issue is caused by repeatable DOI metadata fields not always being an array in the REST API, in this case the `dates` field. This issue comes up now as Fabrica is actually using these fields in the DOI form, using a `fragmentArray`. This is the error we can see in the console.

The short-term fix is to always serialize these fields into an array in the DOI serializer in the API. The long-term fix (faster, but needs updating all DOI records and reindexing) is to make sure these fields are always stored in the database (where we use a JSON field) as an array.
