### ISSUE TITLE
Users should be able to be Client Admin on more than one account

### ISSUE THREAD

**Issue by RachaelKotarski** [datacite/bracco#41]
Users within Fabrica are not able to be Client Admin on more than one Client account. However:

1. On trying to add a User as client admin on a second account, no warning is given to the Provider/Client Admin when this is attempted. In fact, nothing happens at all on clicking 'Save', so it appears that something is simply not working properly
2. If the accounts are managed by different Providers, it would be better for the system to notify the Provider Admin managing the existing relationship that another Provider has tried to add one of their Client Admins to another account. And then either just change them over or ask the original provider/client admin for approval.
3. I know that DataCite advise that it is possible for organisations to have multiple client accounts where necessary. While we don’t do this at the BL, I could imagine that in those situations, you might expect users to be appearing as a client admin on more than one account. So preventing it doesn’t make sense. I accept that it would be unlikely that they would have multiple accounts across different members, and if that’s the main restriction, I fall back to point 2.

This has come up as a user at one of our clients has registered with Fabrica, but it is showing them as associated with another client account. I cannot add them to the account of their current organisation until they are removed by the other provider.

**Comment by CyndieNRC** [comment]
I have run into this issue as well.
I have use cases where one person (one ORCID) has multiple admin rights,  either
1. The person is both BOTH a provider admin and a client admin
OR
2. The person is a client admin with more than one client group. I only have one such case now but can easily see there being similar situations in the future.

**Comment by mfenner** [comment]
@CyndieNRC you can be both a provider admin and client admin.

Can you explain the client groups a bit more?

**Comment by CyndieNRC** [comment]
Definitely.
DataCite Canada has a provider account (National Research Council Canada)

There is also a group on our campus handling the NRC Publications repository and they have a client account (National Research Council)

One NRC staff member has recently been assigned to be my backup for DataCite Canada. She is also the long time lead in running the repository account.

As such, I first added her as a provider admin when we were both learning Fabrica. In December, I tried to add her as a client admin for the repository account. Each time I triewd to add her, she did not appear under the client account. I thought (as Rachel notes above) that the system was just failing tot ake any action. So I tried several times and then sent an email to 'support@datacite.org' (ticket 7407).

I realized shortly afterwards that indeed an action had occurred but a very unexpected one. Sophie was still listed in the DataCite Canada provider account but her status had changed from provider admin to client admin.

So in December you could only see her name under the provider National Research Council Canada account but her status was client admin rather than provider admin there. Her name did not show at all under the client National Research Council account.

That being said, I just checked again now and see that sometimne since Christmas she her name has appeared under both accounts but in both she shows as a client admin for the National Research Council account INSTEAD of the expected client admin role in the National Research Council account client list AND provider admin role in the National Research Council Canada client list.

Thanks!

**Comment by CyndieNRC** [comment]
I should also note that in DataCite Canada the use case of a client organization having multiple accounts is relatively frequent. We have many large organizations spread across big campus or even across the country on multiple campuses. These organization rarely have mature data management plans (in as far as DOI assignment goes) that span the campus. The groups often work very independently.

We several cases where university presses have an account, the repository system has an account and a museum on the campus has an account. For the most part these organizations are so seperate we will nenver have to worry about staff working for more than one of them at a time.

But there are a few cases where a manger has some degree of oversight for more than one of the organizations and wants a client admin account to both.

I am trying to encourage encourage account merges in these cases but I am not sure the clients are going to want to go that route. Which will leave one person needing client admin rights to 2 or more accounts.

**Comment by CyndieNRC** [comment]
One more use case regarding roles.

DataCite Canada has a provider account (National Research Council Canada) and another client account ( DataCite Canada Testing Datacentre)

You will notice that I personally show up (Cynthia Found) under the client "DataCite Canada Testing Datacentre" user list with a role of Provider Admin. 

I find this confusing because I don't think of a provider admin role as being able to be associated visibly with a client account user list. I am thinking Client accounts in Fabrica , as per the nice chart in the November webinar slide deck,  belong to the green client column and can be either client admin or client user. Is that not the case? I am finding these relationship very confusing in terms of figuring out what access and permissions a user will have in any given account.

I (Cynthia Found) also show up under the parent provider account (National Research Council Canada) user list with a provider admin role and also as being associated to client DataCite Canada Testing Datacentre.

Going back to my first use case 2 comments above, will Sophie have provider admin rights in the parent / provider "National Research Council Canada" account given she is listed as a client admin there (and filters as a client on the right side). What sort of client admin rights will I have in the "DataCite Canada Testing Datacentre" - does a provider admin have the same rights as a client admin? 

This situation also does odd things to our ability to filter. There are currently 4 people in provider admin roles with the provider account "National Research Council Canada" (Sophie, myself, Karen and Marcin) but the filer only shows 3. I am guessing this means that either Sophie lost her provider status when I assigned her as a client admin to a client account OR that she is somehow retaining provider rights in the background but that they don't show and we can't filter properly as a result.

Sorry if this use case is less than clear. I am feeling a little lost in my understanding of what should happen. What I thought (but perhaps misunderstood) from the November presentation was that a person would show up in as many provider or client user lists as was appropriate showing their distinct role for that specific account. Does that make sense?

**Comment by CyndieNRC** [comment]
A filter related comment:

The uses cases above also do odd things to our ability to filter. There are currently 4 people in provider admin roles with the provider account "National Research Council Canada" (Sophie, myself, Karen and Marcin) but the filter only shows 3. I am guessing this means that either Sophie lost her provider status when I assigned her as a client admin to a client account OR that she is somehow retaining provider rights in the background but that they don't show and we can't filter properly as a result.

**Comment by CyndieNRC** [comment]
One more question regarding the business rules governing these user roles:

Does Provider admin rights automatically give Client admin rights on all client accounts associated with said provider?

Thanks again!

**Comment by mfenner** [comment]
@CyndieNRC thanks for all the feedback. That was what I was trying to say in my earlier message: a provider admin can do everything the client admin can do, so you don't need to assign both a provider admin and client admin role. There is one place where we are deviating from the MDS here: a provider admin can register and updated DOIs. This is not set in stone, and DOI registration functionality hasn't been implemented yet.

**Comment by CyndieNRC** [comment]
This is starting to come together for me. :)

I do agree with Rachael that a few more system notifications would help. When I tried to add Sophie as a client admin, if the system had returned “Sophie is already a provider admin for this account so does not need to be added as a client admin” then  I think I would have clued in much earlier as to how things were working.

It does still concern me that when I added her as a client admin, that the system appears to have over-written the previous provider admin status without notifying me in any way that it was doing so. It was hours before I realized Fabrica had flipped her status. I think here a “This action will change Sophie from a provider admin to a client admin – Continue???” would have been nice.

I went into Fabrica and flipped Sophie back to provider admin manually but I do have screen captures of everything that happened along the way if you need them at any point.

Thanks Martin!

**Comment by mfenner** [comment]
@CyndieNRC I completely agree: the user registration flow has bugs and needs more documentation/feedback. This is next on my list of work for DOI Fabrica.

**Comment by CyndieNRC** [comment]
I feel badly always just sending bugs.

I am actually in awe how much you have done with so few people. It is quite remarkable and I am very excited to see the finished product.

**Comment by mfenner** [comment]
@CyndieNRC and @RachaelKotarski we have changed the authentication in https://doi.test.datacite.org to use your MDS username/password instead of personalized accounts. There are a number of reasons for this, but this also allows multiple client accounts.

This is currently undergoing testing, your feedback would be appreciated.

**Comment by CyndieNRC** [comment]
Sure Martin. When you say this allows multiple clients accounts, do you mean each client can have more than one account and password?

**Comment by mfenner** [comment]
Yes @CyndieNRC. As the accounts are not per person, you can log in into multiple accounts, e.g. for each client. Not the same as managing multiple clients at once, but should probably be ok for most use cases mentioned in this GitHub issue.

**Comment by CyndieNRC** [comment]
Hi again. Looking good from my initial pokes. I checked from the provider point of view only though. I think I need to login as a client and make sure they can only see their own client account information. I am off on training this week so won't get a proper chance to poke until Monday. Sorry.

**Comment by mfenner** [comment]
@CyndieNRC we have checked the client views and that looks as expected. But please do further testing when there is time.

**Comment by mfenner** [comment]
Closing this, as the authentication has changed and the original issue is no longer relevant.
