### ISSUE TITLE
Adding ISSN to existing DOI in relatedIdentifiers field in the form generates error

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#415]
### Expected Behaviour

Possible to add related identifiers to existing DOI via Fabrica form

### Current Behaviour

Adding ISSN to existing DOI in relatedIdentifiers field in the form generates " To save this DOI, first resolve the errors with these properties: relatedIdentifier. "

### Steps to Reproduce

<img width="1186" alt="Screen Shot 2020-05-25 at 15 35 33" src="https://user-images.githubusercontent.com/44582654/82817521-6af95280-9e9d-11ea-86e5-4328a79409de.png">

<img width="1079" alt="Screen Shot 2020-05-25 at 15 29 47" src="https://user-images.githubusercontent.com/44582654/82817357-28d01100-9e9d-11ea-91ea-4f5f2d13f959.png">

NOTE: the type appears in caps in drop down ISSN and small letters once selected issn

### Context (Environment)

Fabrica Form

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ns45)

**Comment by kjgarza** [comment]
effectively @MaryHirsch the issue here is the case-conversion  of the related Identifier Type. @mfenner do we actually need to convert the `relatedIdentifierType` to pascal case? Most of them are `acronyms` I do not think they need to be converted in the UI. Any comments?

https://github.com/datacite/bracco/blob/82a11ce/app/components/doi-related-identifier.js#L203

**Comment by mfenner** [comment]
I agree @kjgarza.
