### ISSUE TITLE
API doesn't fail when nameIdentifiers is sent as a object rather the as an array

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#444]
### Expected Behaviour

Access list of DOIs by clicking on DOIs tab

### Current Behaviour

DOIs tab blank

<img width="1322" alt="Screen Shot 2020-07-03 at 14 26 41" src="https://user-images.githubusercontent.com/44582654/86469210-3e0c4b00-bd39-11ea-9ba4-d60bb0262b03.png">

### Steps to Reproduce

https://doi.datacite.org/repositories/bf.discover/dois

### Context (Environment)

it can be found in the api

https://api.datacite.org/dois?client-id=bf.discover
https://api.datacite.org/clients/bf.discover/dois

![image](https://user-images.githubusercontent.com/1092861/86561236-8063a100-bf60-11ea-8ce2-94917840e3a2.png)

Fabrica production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nutx)

**Comment by kjgarza** [comment]
maybe related to https://app.frontapp.com/open/msg_e9onoph

**Comment by kjgarza** [comment]
or maybe related to https://app.frontapp.com/open/msg_45cz9mr

**Comment by kjgarza** [comment]
none of the DOIs seem to have a `source` https://api.datacite.org/clients/bf.discover/dois

**Comment by kjgarza** [comment]
commented all other   fragmentArray declaration in the DOI model until i found the one that is failing. that was name_identifiers. For some reasons bf.dissocvery was able to mint doi with an object rather than an array in this field.

// contributors: fragmentArray('contributor', { defaultValue: [] }),


![image](https://user-images.githubusercontent.com/1092861/86566707-5fa04900-bf6a-11ea-8608-e949b3e56c03.png)

**Comment by mfenner** [comment]
Good catch? Is nameIdentifiers as object possible with the form or one of the APIs?

**Comment by kjgarza** [comment]
The form doesn't allow that. it must have been made with an API. It seems to be many of their dois (or all), Which is strange.

I don't think they can use XML upload to fix it,because one cannot go into the doi page. we will probably need to update them via a rake tasks. They only need a `touch` to be fixed. there is no need to modify the metadata.

**Comment by mfenner** [comment]
Makes sense, thanks.

**Comment by jwagenaar** [comment]
Hi all, thanks for looking into this. Copying our engineer @JeremyLecoeur in case you have any questions.

**Comment by JeremyLecoeur** [comment]
Hello, I'm the dev responsible on blackfynn side for the DOI requests change that added the name identifier. I see where I made a mistake and I can correct it easily. You were correct in assuming we use the API to update the DOIs. I'm surprised that I did not receive an error code in response since the request was malformed.

**Comment by kjgarza** [comment]
@JeremyLecoeur could you let us know which endpoint did you use? We can review the validation on that endpoint to avoid that problem in the future.

**Comment by JeremyLecoeur** [comment]
I used the PATCH `https://api.datacite.org/dois/{doi}` endpoint

**Comment by kjgarza** [comment]
@JeremyLecoeur could you paste the payload **you were** sending before ? that would help me to define changes in the validation if needed
