### ISSUE TITLE
DOI record shows DOI in findable state, in the list view it shows DOI as draft

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#448]
### Expected Behaviour

DOI "Findable" state tag is seen in DOI record and list view 

### Current Behaviour

DOI record shows DOI as findable, in list view it shows DOI as draft

### Steps to Reproduce

https://doi.datacite.org/dois/10.26183%2Fwkx4-c175
<img width="964" alt="Screen Shot 2020-07-20 at 15 50 01" src="https://user-images.githubusercontent.com/44582654/87947643-eba28c80-caa3-11ea-94bc-829c9d875d45.png">

https://doi.datacite.org/repositories/ardcx.wsu/dois
<img width="1308" alt="Screen Shot 2020-07-20 at 15 50 10" src="https://user-images.githubusercontent.com/44582654/87947645-ecd3b980-caa3-11ea-9e3b-f276498d0087.png">

### Context (Environment)

Fabrica

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nx91)

**Comment by richardhallett** [comment]
The problem here is the metadata did not get indexed correctly in elasticsearch, so the actual bug might be something to do with a certain workflow that doesnt trigger updates.
However in this specific case, this is a per doi issue for this person and not a bug as the fix is to update the DOI.
I did this with file upload in fabrica and now this works.
