### ISSUE TITLE
New test DOIs do not resolve via test handle

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#482]
### Expected Behaviour

Test DOIs resolve via the handle server.

### Current Behaviour

New test DOIs not resolving

### Steps to Reproduce

1. resolves via test handle: https://handle.stage.datacite.org/10.17863/cam.318
2. does not resolve via test handle: https://handle.stage.datacite.org/10.11570/20.0060.test

### Context (Environment)

Fabrica test

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o8yd)

**Comment by richardhallett** [comment]
Additional example 10.23664/d.2020.0102115178

**Comment by richardhallett** [comment]
The problem was not related to bracco but the underlying test handle server was throwing Java exceptions, I've restarted it and now DOIs appear to be registering successfully.
The above DOIs i've fixed manually by updating.
Other DOIs that are not found in the handle system will need to be sent an update request which will force a registration in the test handle service.
