### ISSUE TITLE
Investigate why CDCC DOIs not indexed in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#484]
CCDC report issue updating DOIs (422).
This DOI: https://doi.datacite.org/dois/10.5517%2Fccdc.csd.cc24xyz0 cannot be found in Fabrica, but does appear to be indexed under the correct repository.
This is affecting 34 records with prefix 10.5517

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o9qt)

**Comment by richardhallett** [comment]
Closing as no underlying bug, just some DOIs that got lost, this I believe was due to the timespan during a migration that seems to have affected a small number of dois.

I've gone through via the DOI and imported these dois so they appear correctly in the Elasticsearch index.

No data was lost during this process.
