### ISSUE TITLE
Not possible to add 2022 in publication year in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#507]
#### Expected Behaviour

Fabrica accepts publication years in the future for embargoed content

#### Current Behaviour

The year 2022 is not accepted by the publication year field

#### Steps to Reproduce

<img width="1273" alt="Screen Shot 2021-01-29 at 15 23 47" src="https://user-images.githubusercontent.com/44582654/106286522-08cfc900-6246-11eb-985c-63531131acb4.png">

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2odw5)

**Comment by richardhallett** [comment]
This isn't a bug as it is working as intended, the form says "Must be a year between 1000 and 2021."

The user can workaround this using the file upload if desired. Otherwise this would be a feature change. I'm not sure of the original reasoning for this field being limited to this date range.

I've removed the bug label and put it as enhancement.

**Comment by mfenner** [comment]
In previous years we have allowed entering a publicationYear one year into the future. This is currently hard-coded, so would need to be adjusted once a year if we keep the pattern.

**Comment by sfisher** [comment]
It looks like this has been fixed in code (thanks!). Yet I'm still seeing limits to 2021 or before when I use the production Fabrica `Update DOI (form)` and changing from registered/findable.  It doesn't allow saving with the message about 2021 being the last year.

Maybe this hasn't been rolled in or deployed yet?  Otherwise this bug still seems to exist.

**Comment by KellyStathis** [comment]
Hi @sfisher, could you please try clearing your browser cache? You should then see the publication year field accepts years including 2022 as shown below:
![PublicationYear](https://user-images.githubusercontent.com/17298577/208978060-3a3f4a49-0166-4a25-86b8-9e125e2ba438.png)

**Comment by sfisher** [comment]
Thanks!  I got it to work by clearing the cache.  I'm surprised it cached that for so long!
