### ISSUE TITLE
Prefix 10.17883  appears to be assigned to a deleted repository in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#512]
#### Expected Behaviour

Prefix cannot be assigned to a deleted repository. The prefix must be unassigned before the repository can be deleted

#### Current Behaviour

Prefix 10.17883 appears to be assigned to a deleted repository gesis.evhn

#### Steps to Reproduce

Here it does not appear assigned to a repository: https://doi.datacite.org/providers/xgdf/prefixes/10.17883  
Here is does appear to be assigned to a repository: https://doi.datacite.org/repositories/gesis.evhn/prefixes/10.17883 

### Context (Environment)

Fabrica

**Comment by richardhallett** [comment]
I've removed the prefix for the specific test case of 10.17883 from the deleted repository, this can be done from the prefixes screen in Fabrica.

The actual bug does seem to be that when a repository is deleted the prefix remains attached, this may or may not be intended and needs further thought.

**Comment by richardhallett** [comment]
I'm closing this as the original bug was solved.
The problem mentioned with not removing a prefix from a deleted repository is I think correct with the current workflow, this is because if we removed it and it became available again this might also be unintended reclaimed, therefore I think it's better than prefixes should be left intact with repository.
