### ISSUE TITLE
DOI with colon symbol in suffix not retrieved with a search in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#517]
#### Expected Behaviour

Search in Fabrica for 10.2314/kxp:1738669661 retrieves the corresponding DOI

#### Current Behaviour

The DOI is only retrieved when searching *1738669661*

#### Steps to Reproduce

https://doi.datacite.org/dois?page=NaN&query=*1738669661*&sort=relevance

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2of2t)

**Comment by mfenner** [comment]
A number of characters have special meaning in queries in Fabrica and the DataCite REST API:  `+ - = && || > < ! ( ) { } [ ] ^ " ~ * ? : \ / `. If they are part of the query string, they have to be escaped with an extra backslash. 

Also, some characters (pretty much the same list) will be escaped when they become part of the URL, e.g. `:` becomes `%3A`. 

Other search indexes for DOIs may show different behaviour, this is caused by the Elasticsearch [query_string_parser](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) which makes it possible to search specific fields indicated in the query.

The query in this example is correctly written as https://doi.datacite.org/dois?page=NaN&query=10.2314%2Fkxp%5C%3A1738669661&sort=relevance.
