### ISSUE TITLE
The affiliation information is lost from the contributor attribute when a DOI is update via the form

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#550]
#### Expected Behaviour

The affiliation metadata in the contributor field is maintained after updating via the form

#### Current Behaviour

The affiliation information is lost from the contributor attribute when a user updates a DOI via the form

#### Steps to Reproduce

1. Create a DOI with a contributor and contributor affiliation
2. Update DOI via the form
3. the contributor affiliation appears to have been lost
4. https://doi.test.datacite.org/dois/10.80223%2Ftest_doi_5e813af66fe20

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oi6t)

**Comment by codycooperross** [comment]
I was able to reproduce this behavior but only by performing a hard refresh before or after going into the Fabrica form to update. Not sure if that narrows down the issue.

**Comment by svogt0511** [comment]
@codycooperross - I am glad you noted that a hard refresh allows you to reproduce the bug because I was not able to reproduce it without that. I need to check into it more, but I think what is happening is that the hard refresh wipes the affiliation data out of the Ember store (basically a cache). Then when you go into the form to do an update, the affiliation data is not brought back into the browser and when you save the updated form, that is when the data is lost.  Still needs a little more research to absolutely verify that and figure out what to do.
