### ISSUE TITLE
Set password functionality not working if contact information not included

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#560]
#### Expected Behaviour

The password can always be set even if the contact roles have not been added

#### Current Behaviour

The "Set password" function in the "settings" tab does not allow users to set password unless the contact roles have been added

#### Steps to Reproduce

<img width="954" alt="Screen Shot 2021-07-20 at 17 44 13" src="https://user-images.githubusercontent.com/44582654/126354951-5cc6cdcb-c966-4327-8b4b-30806ecc0e36.png">

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oj6d)

**Comment by svogt0511** [comment]
Should be. Richard put in a fix for it and I tested it. I will close it.

Suzanne Vogt | Application Developer | DataCite
E: ***@***.*** | ORCID
W: datacite.org | Blog | Twitter | LinkedIn
Support Desk | Support Site | PID Forum

--- original message ---
On October 18, 2021, 4:09 AM EDT ***@***.*** wrote:



@svogt0511 I think this is fixed right?

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
