### ISSUE TITLE
DOI search in Fabrica does nothing

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#571]
#### Expected Behaviour

Possible to search through index for a specific DOI

#### Current Behaviour

When logged in with the admin account, the DOI search does not retrieve and results.

#### Steps to Reproduce

1. Go to https://doi.datacite.org/dois
2. Search for any DOI.
3. nothing happens

### Context (Environment)

Fabrica

**Comment by codycooperross** [comment]
This appears to have been resolved.

**Comment by KellyStathis** [comment]
@codycooperross When I search for any specific DOI, I get "An error occured fetching DOIs. Please contact DataCite Support." For example: https://doi.datacite.org/dois?page=NaN&query=https%3A%2F%2Fdoi.org%2F10.5281%2Fzenodo.7114182&sort=relevance. Is this a different issue?

**Comment by codycooperross** [comment]
@KellyStathis I was confused because non-URL DOI searches (as well as other searches) do work, which is what I tested: https://doi.datacite.org/dois?page=NaN&query=10.5281%2Fzenodo.7114182&sort=relevance I'll reopen with the assumption that the URL form is at issue. The query the search relies on may not be searching the ES field that includes the complete DOI URL.

**Comment by richardhallett** [comment]
Yes the DOI search box is for the Datacite DOIs without the URL i.e. "10.5281/zenodo.7114182" not "https://doi.org/10.5281/zenodo.7114182" 
This is most likely due to being pased to elasticsearch "query_string" and it needs proper escaping.

TBH This isn't really something that can be addressed as a bug it's more a limitation of the design of the search functionality, I think it'd need to be addressed on a feature to expand what is searchable and what is not for this search field.

Therefore with that in mind I am closing this out, If it's a requirement users can search based on full DOI urls then i'd put it to the roadmap suggestions,
