### ISSUE TITLE
Consortium lead accounts cannot create repositories in test

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#587]
#### Expected Behaviour

When logged in with a Consortium account it should be possible to create a repository

#### Current Behaviour

Currently not possible to create a repository (only when logged in with consortum account, it. does work with admin)

#### Steps to Reproduce

1. Log in with DC in test
2. Try to create a repository
3. No reponse

### Context (Environment)

Fabrica test

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ppw5)

**Comment by MaryHirsch** [comment]
@svogt0511 I can't reproduce this either, I think you can close it

**Comment by svogt0511** [comment]
I am closing this issue.  Just a couple of notes.  There was a problem when this issue was first written up.  It only occurred in test. It seems to have been a transient problem related to the need for reindexing elastic search in test, which has been done since then.  This has been tested and seems to work fine now, so I am closing this issue.
